# Generated by Django 4.2.11 on 2024-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_profile_id_user_remove_profile_profliepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True),
        ),
    ]
