# Generated by Django 4.2.11 on 2024-03-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
