# Generated by Django 4.2.11 on 2024-03-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_profile_id_user_remove_profile_profliepic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
