# Generated by Django 4.2.11 on 2024-03-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_options_remove_post_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
