# Generated by Django 4.2.11 on 2024-03-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_profile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
