# Generated by Django 4.2.11 on 2024-03-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
