# Generated by Django 4.2.11 on 2024-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_user_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
