# Generated by Django 4.2.11 on 2024-03-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
