# Generated by Django 4.2.11 on 2024-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_comment_updated_on_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='5907.jpeg', upload_to=''),
        ),
    ]
