# Generated by Django 4.2.11 on 2024-03-14 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_post_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='pro_pic'),
        ),
    ]
